#!/usr/bin/env npx ts-node

import * as readline from 'readline'
import * as fs from 'fs'
import * as path from 'path'

const rl = readline.createInterface({ input: process.stdin, output: process.stdout })

function ask(question: string): Promise<string> {
  return new Promise(resolve => rl.question(question, resolve))
}

async function main() {
  console.log('\n===========================================')
  console.log('  ARSI PLATFORM -- Client Provisioning')
  console.log('===========================================\n')

  // 1. Gather client details
  const clientName = await ask('Business name: ')
  const clientSlug = await ask('URL slug (lowercase, no spaces): ')
  const clientEmail = await ask('Business email: ')
  const clientDomain = await ask('Domain (e.g., clientname.com): ')
  const city = await ask('City: ')
  const state = await ask('State: ')

  // Module selection
  console.log('\n-- Enable Modules --')
  const booking = (await ask('Enable booking module? (y/n): ')).toLowerCase() === 'y'
  const ecommerce = (await ask('Enable ecommerce module? (y/n): ')).toLowerCase() === 'y'
  const blog = (await ask('Enable blog module? (y/n): ')).toLowerCase() === 'y'
  const leads = (await ask('Enable leads module? (y/n): ')).toLowerCase() === 'y'

  // Hosting mode selection
  console.log('\n-- Hosting Mode --')
  console.log('  1. Arsi Managed — site lives on your Vercel, Command Center monitoring, client pays $19/mo')
  console.log('  2. Self Hosted  — client owns their Vercel, no monitoring, no Arsi branding')
  let hostingChoice = ''
  while (hostingChoice !== '1' && hostingChoice !== '2') {
    hostingChoice = (await ask('\n> Choose hosting mode (1 or 2): ')).trim()
  }
  const isManaged = hostingChoice === '1'

  // Supabase details
  console.log('\n-- Supabase Credentials --')
  const supabaseUrl = await ask('Supabase project URL: ')
  const supabaseAnonKey = await ask('Supabase anon key: ')
  const supabaseServiceKey = await ask('Supabase service role key: ')

  console.log('\nProvisioning...\n')

  // 2. Generate site.config.ts
  const arsiPlatformBlock = isManaged
    ? `  // -- 13. ARSI PLATFORM MODE --
  arsiPlatform: {
    // HOSTING MODE:
    // 'local-business' — Arsi managed hosting
    //   Site lives on Arsi's Vercel account
    //   Monitored via Command Center
    //   $19/mo recurring revenue
    //   You handle all deployments + updates
    mode: 'local-business' as 'local-business' | 'developer',
    monitoringEnabled: true,
    showPoweredBy: true,
    commandCenterUrl: 'https://arsi-platform-dashboard.vercel.app',
    developer: {
      selfHosted: false,
      customBranding: false,
      hideArsiFooter: false,
    },
  },`
    : `  // -- 13. ARSI PLATFORM MODE --
  arsiPlatform: {
    // HOSTING MODE:
    // 'developer' — Self hosted
    //   Client owns their Vercel account
    //   No monitoring overhead
    //   One-time setup fee
    //   No Arsi branding
    mode: 'developer' as 'local-business' | 'developer',
    monitoringEnabled: false,
    showPoweredBy: false,
    commandCenterUrl: '',
    developer: {
      selfHosted: true,
      customBranding: true,
      hideArsiFooter: true,
    },
  },`

  const siteConfigContent = `// ============================================================
// ARSI PLATFORM -- Client Site Configuration
// Generated by provision-client.ts
// ============================================================

export const siteConfig = {
  // -- 1. BUSINESS IDENTITY --
  business: {
    name: "${clientName}",
    tagline: "Welcome to ${clientName}",
    email: "${clientEmail}",
    phone: "",
    address: "",
    city: "${city}",
    state: "${state}",
    zip: "",
    logo: "/images/logo.png",
    favicon: "/images/favicon.ico",
  },

  // -- 2. BRANDING & THEME --
  branding: {
    theme: "warm" as "warm" | "corporate" | "bold",
    primaryColor: '#c2410c',
    accentColor: '#d97706',
    fontHeading: 'Playfair Display',
    fontBody: 'DM Sans',
    heroImage: '/images/hero.jpg',
    logoText: true,
    animationStyle: 'subtle' as 'subtle' | 'dramatic' | 'none',
  },

  // -- 3. MODULE FLAGS --
  modules: {
    booking: ${booking},
    ecommerce: ${ecommerce},
    blog: ${blog},
    leads: ${leads},
  },

  // -- 4. AUTHENTICATION --
  auth: {
    enabled: true,
    requireEmailVerification: true,
    providers: ["email"] as ("email" | "google" | "facebook")[],
  },

  // -- 5. PAYMENTS --
  payments: {
    enabled: ${ecommerce},
    provider: "stripe" as "stripe" | "paypal" | "both",
    currency: "usd",
    testMode: true,
  },

  // -- 6. EMAIL AUTOMATION --
  email: {
    fromName: "${clientName}",
    fromEmail: "hello@${clientDomain}",
    replyTo: "hello@${clientDomain}",
    templates: {
      welcome: true,
      bookingConfirmation: ${booking},
      orderConfirmation: ${ecommerce},
      passwordReset: true,
      adminNewLead: ${leads},
    },
  },

  // -- 7. PAGES & CONTENT --
  pages: {
    home: { enabled: true, title: "Home" },
    about: { enabled: true, title: "About Us" },
    services: { enabled: true, title: "Services" },
    contact: { enabled: true, title: "Contact" },
    shop: { enabled: ${ecommerce}, title: "Shop" },
    book: { enabled: ${booking}, title: "Book Now" },
    blog: { enabled: ${blog}, title: "Blog" },
  },

  // -- 8. SEO & ANALYTICS --
  seo: {
    defaultTitle: "${clientName}",
    titleTemplate: "%s | ${clientName}",
    defaultDescription: "Welcome to ${clientName}",
    ogImage: "/images/og-image.png",
    googleAnalyticsId: "",
    facebookPixelId: "",
  },

  // -- 9. INTEGRATIONS --
  integrations: {
    googleMaps: "",
    facebookPage: "",
    instagram: "",
    twitter: "",
    linkedin: "",
  },

  // -- 10. ADMIN NOTIFICATIONS --
  notifications: {
    adminEmail: "${clientEmail}",
    notifyOnNewLead: ${leads},
    notifyOnNewBooking: ${booking},
    notifyOnNewOrder: ${ecommerce},
    notifyOnNewUser: true,
  },

  // -- 11. LOCATION --
  location: {
    address: '',
    city: '${city}',
    state: '${state}',
    zip: '',
    googleMapsEmbed: '',
    showMapOnContact: true,
    showMapOnHome: true,
    hours: [
      { day: 'Monday - Friday', hours: '9:00 AM - 6:00 PM' },
      { day: 'Saturday', hours: '10:00 AM - 4:00 PM' },
      { day: 'Sunday', hours: 'Closed' },
    ],
  },

  // -- 12. RESTAURANT (optional) --
  restaurant: {
    enabled: false,
    menuPdf: '',
    reservationsUrl: '',
    featuredDishes: [] as { name: string; description: string; price: string; image: string }[],
  },

${arsiPlatformBlock}
} as const

export type SiteConfig = typeof siteConfig
`

  const configPath = path.join(__dirname, '..', 'site.config.ts')
  fs.writeFileSync(configPath, siteConfigContent)
  console.log('  site.config.ts generated')

  // 3. Generate .env.local
  const cronSecret = Math.random().toString(36).slice(2) + Math.random().toString(36).slice(2)
  const envContent = `NEXT_PUBLIC_SUPABASE_URL=${supabaseUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${supabaseAnonKey}
SUPABASE_SERVICE_ROLE_KEY=${supabaseServiceKey}
RESEND_API_KEY=
RESEND_FROM_EMAIL=hello@${clientDomain}
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=
CLOUDFLARE_R2_ACCESS_KEY_ID=
CLOUDFLARE_R2_SECRET_ACCESS_KEY=
CLOUDFLARE_R2_ENDPOINT=
CLOUDFLARE_R2_BUCKET=arsi-backups
CLIENT_SLUG=${clientSlug}
CRON_SECRET=${cronSecret}
${isManaged ? 'DISCORD_WEBHOOK_DAILY_REPORTS=' : 'DISCORD_WEBHOOK='}
${isManaged ? 'COMMAND_CENTER_URL=https://arsi-platform-dashboard.vercel.app' : ''}
`
  const envPath = path.join(__dirname, '..', '.env.local')
  fs.writeFileSync(envPath, envContent)
  console.log('  .env.local generated')

  // 4. Output summary
  console.log('\n===========================================')
  console.log('  PROVISIONING COMPLETE')
  console.log('===========================================')

  if (isManaged) {
    console.log('')
    console.log('  ✅ Configured for Arsi Managed hosting')
    console.log('')
    console.log('  📋 NEXT STEPS:')
    console.log('  1. Deploy to YOUR Vercel account:')
    console.log('     - Go to vercel.com → Add New Project')
    console.log('     - Import arsi-platform → Root Directory: apps/starter-app')
    console.log('     - Add env vars (listed below)')
    console.log('     - Deploy')
    console.log('')
    console.log('  2. Connect client domain in Vercel dashboard')
    console.log('')
    console.log('  3. Site will be automatically monitored via Command Center')
    console.log('')
    console.log('  4. Send client invoice for $19/mo')
    console.log('')
    console.log('  5. Run the SQL schema in Supabase SQL Editor:')
    console.log('     supabase/schema.sql')
    console.log('')
    console.log('  6. Create an admin user in Supabase Auth')
    console.log('     Then insert admin row in users table with role=\'admin\'')
    console.log('')
    console.log('  ENV VARS TO ADD IN VERCEL:')
    console.log(`  NEXT_PUBLIC_SUPABASE_URL=${supabaseUrl}`)
    console.log(`  NEXT_PUBLIC_SUPABASE_ANON_KEY=${supabaseAnonKey}`)
    console.log(`  SUPABASE_SERVICE_ROLE_KEY=${supabaseServiceKey}`)
    console.log(`  CLIENT_SLUG=${clientSlug}`)
    console.log(`  CRON_SECRET=${cronSecret}`)
    console.log('  RESEND_API_KEY=<your-resend-key>')
    console.log(`  RESEND_FROM_EMAIL=hello@${clientDomain}`)
    if (ecommerce) {
      console.log('  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=<your-stripe-pk>')
      console.log('  STRIPE_SECRET_KEY=<your-stripe-sk>')
      console.log('  STRIPE_WEBHOOK_SECRET=<your-stripe-webhook-secret>')
    }
    console.log('  COMMAND_CENTER_URL=https://arsi-platform-dashboard.vercel.app')
    console.log('  DISCORD_WEBHOOK_DAILY_REPORTS=<your-discord-webhook>')
    console.log('  CLOUDFLARE_R2_ACCESS_KEY_ID=<your-r2-access-key>')
    console.log('  CLOUDFLARE_R2_SECRET_ACCESS_KEY=<your-r2-secret-key>')
    console.log('  CLOUDFLARE_R2_ENDPOINT=<your-r2-endpoint>')
    console.log('  CLOUDFLARE_R2_BUCKET=arsi-backups')
  } else {
    console.log('')
    console.log('  ✅ Configured for Self Hosted deployment')
    console.log('')
    console.log('  📋 NEXT STEPS FOR CLIENT:')
    console.log('  1. Create a free Vercel account at vercel.com')
    console.log('  2. Create a free Supabase account at supabase.com')
    console.log('  3. Share this repo with them or deploy on their behalf')
    console.log('')
    console.log('  4. They need these env vars in their Vercel project:')
    console.log(`     NEXT_PUBLIC_SUPABASE_URL=${supabaseUrl}`)
    console.log(`     NEXT_PUBLIC_SUPABASE_ANON_KEY=${supabaseAnonKey}`)
    console.log(`     SUPABASE_SERVICE_ROLE_KEY=${supabaseServiceKey}`)
    console.log(`     CLIENT_SLUG=${clientSlug}`)
    console.log(`     CRON_SECRET=${cronSecret}`)
    console.log('     RESEND_API_KEY=<their-resend-key>')
    console.log(`     RESEND_FROM_EMAIL=hello@${clientDomain}`)
    if (ecommerce) {
      console.log('     NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=<their-stripe-pk>')
      console.log('     STRIPE_SECRET_KEY=<their-stripe-sk>')
      console.log('     STRIPE_WEBHOOK_SECRET=<their-stripe-webhook-secret>')
    }
    console.log('')
    console.log('  5. Run the schema in their Supabase SQL Editor:')
    console.log('     File: supabase/schema.sql')
    console.log('')
    console.log('  6. Create their admin user in Supabase Authentication')
    console.log('     Then insert admin row in users table with role=\'admin\'')
    console.log('')
    console.log('  📄 Full setup guide: DEVELOPER.md')
    console.log('')
    console.log('  💰 BILLING: Charge one-time setup fee instead of monthly')
  }

  console.log('\n===========================================\n')

  rl.close()
}

main().catch(console.error)
